// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: blob_relay_streaming.proto
#ifndef GRPC_blob_5frelay_5fstreaming_2eproto__INCLUDED
#define GRPC_blob_5frelay_5fstreaming_2eproto__INCLUDED

#include "blob_relay_streaming.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace data_relay_grpc {
namespace blob_relay {
namespace proto {

// Transfer BLOB data using gRPC streaming.
class BlobRelayStreaming final {
 public:
  static constexpr char const* service_full_name() {
    return "data_relay_grpc.blob_relay.proto.BlobRelayStreaming";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Download BLOB data.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>> Get(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>>(GetRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>> AsyncGet(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>>(AsyncGetRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>> PrepareAsyncGet(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>>(PrepareAsyncGetRaw(context, request, cq));
    }
    // Upload BLOB data.
    std::unique_ptr< ::grpc::ClientWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>> Put(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>>(PutRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>> AsyncPut(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>>(AsyncPutRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>> PrepareAsyncPut(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>>(PrepareAsyncPutRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Download BLOB data.
      virtual void Get(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* request, ::grpc::ClientReadReactor< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* reactor) = 0;
      // Upload BLOB data.
      virtual void Put(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::ClientWriteReactor< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* GetRaw(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* AsyncGetRaw(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* PutRaw(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* AsyncPutRaw(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* PrepareAsyncPutRaw(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>> Get(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>>(GetRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>> AsyncGet(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>>(AsyncGetRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>> PrepareAsyncGet(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>>(PrepareAsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>> Put(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>>(PutRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>> AsyncPut(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>>(AsyncPutRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>> PrepareAsyncPut(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>>(PrepareAsyncPutRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Get(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* request, ::grpc::ClientReadReactor< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* reactor) override;
      void Put(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::ClientWriteReactor< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* GetRaw(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request) override;
    ::grpc::ClientAsyncReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* AsyncGetRaw(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* PutRaw(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response) override;
    ::grpc::ClientAsyncWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* AsyncPutRaw(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* PrepareAsyncPutRaw(::grpc::ClientContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Get_;
    const ::grpc::internal::RpcMethod rpcmethod_Put_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Download BLOB data.
    virtual ::grpc::Status Get(::grpc::ServerContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* request, ::grpc::ServerWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* writer);
    // Upload BLOB data.
    virtual ::grpc::Status Put(::grpc::ServerContext* context, ::grpc::ServerReader< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* reader, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Get() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* /*request*/, ::grpc::ServerWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* request, ::grpc::ServerAsyncWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Put : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Put() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Put() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Put(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* /*reader*/, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPut(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::data_relay_grpc::blob_relay::proto::PutStreamingResponse, ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Get<WithAsyncMethod_Put<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Get() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::data_relay_grpc::blob_relay::proto::GetStreamingRequest, ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* request) { return this->Get(context, request); }));
    }
    ~WithCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* /*request*/, ::grpc::ServerWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Put : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Put() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* response) { return this->Put(context, response); }));
    }
    ~WithCallbackMethod_Put() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Put(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* /*reader*/, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* Put(
      ::grpc::CallbackServerContext* /*context*/, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Get<WithCallbackMethod_Put<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Get() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* /*request*/, ::grpc::ServerWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Put : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Put() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Put() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Put(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* /*reader*/, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Get() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* /*request*/, ::grpc::ServerWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Put : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Put() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Put() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Put(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* /*reader*/, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPut(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Get() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Get(context, request); }));
    }
    ~WithRawCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* /*request*/, ::grpc::ServerWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Put : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Put() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->Put(context, response); }));
    }
    ~WithRawCallbackMethod_Put() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Put(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest>* /*reader*/, ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* Put(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Get() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::data_relay_grpc::blob_relay::proto::GetStreamingRequest, ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::data_relay_grpc::blob_relay::proto::GetStreamingRequest, ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* streamer) {
                       return this->StreamedGet(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* /*request*/, ::grpc::ServerWriter< ::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGet(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::data_relay_grpc::blob_relay::proto::GetStreamingRequest,::data_relay_grpc::blob_relay::proto::GetStreamingResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Get<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Get<Service > StreamedService;
};

}  // namespace proto
}  // namespace blob_relay
}  // namespace data_relay_grpc


#endif  // GRPC_blob_5frelay_5fstreaming_2eproto__INCLUDED
