// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blob_reference.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_blob_5freference_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_blob_5freference_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_blob_5freference_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_blob_5freference_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_blob_5freference_2eproto;
namespace data_relay_grpc {
namespace blob_relay {
namespace proto {
class BlobReference;
struct BlobReferenceDefaultTypeInternal;
extern BlobReferenceDefaultTypeInternal _BlobReference_default_instance_;
}  // namespace proto
}  // namespace blob_relay
}  // namespace data_relay_grpc
PROTOBUF_NAMESPACE_OPEN
template<> ::data_relay_grpc::blob_relay::proto::BlobReference* Arena::CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::BlobReference>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace data_relay_grpc {
namespace blob_relay {
namespace proto {

// ===================================================================

class BlobReference final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:data_relay_grpc.blob_relay.proto.BlobReference) */ {
 public:
  inline BlobReference() : BlobReference(nullptr) {}
  ~BlobReference() override;
  explicit PROTOBUF_CONSTEXPR BlobReference(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BlobReference(const BlobReference& from);
  BlobReference(BlobReference&& from) noexcept
    : BlobReference() {
    *this = ::std::move(from);
  }

  inline BlobReference& operator=(const BlobReference& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlobReference& operator=(BlobReference&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BlobReference& default_instance() {
    return *internal_default_instance();
  }
  static inline const BlobReference* internal_default_instance() {
    return reinterpret_cast<const BlobReference*>(
               &_BlobReference_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BlobReference& a, BlobReference& b) {
    a.Swap(&b);
  }
  inline void Swap(BlobReference* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BlobReference* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BlobReference* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BlobReference>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BlobReference& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BlobReference& from) {
    BlobReference::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlobReference* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "data_relay_grpc.blob_relay.proto.BlobReference";
  }
  protected:
  explicit BlobReference(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStorageIdFieldNumber = 1,
    kObjectIdFieldNumber = 2,
    kTagFieldNumber = 3,
  };
  // uint64 storage_id = 1;
  void clear_storage_id();
  uint64_t storage_id() const;
  void set_storage_id(uint64_t value);
  private:
  uint64_t _internal_storage_id() const;
  void _internal_set_storage_id(uint64_t value);
  public:

  // uint64 object_id = 2;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // uint64 tag = 3;
  void clear_tag();
  uint64_t tag() const;
  void set_tag(uint64_t value);
  private:
  uint64_t _internal_tag() const;
  void _internal_set_tag(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:data_relay_grpc.blob_relay.proto.BlobReference)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t storage_id_;
    uint64_t object_id_;
    uint64_t tag_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_blob_5freference_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BlobReference

// uint64 storage_id = 1;
inline void BlobReference::clear_storage_id() {
  _impl_.storage_id_ = uint64_t{0u};
}
inline uint64_t BlobReference::_internal_storage_id() const {
  return _impl_.storage_id_;
}
inline uint64_t BlobReference::storage_id() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.BlobReference.storage_id)
  return _internal_storage_id();
}
inline void BlobReference::_internal_set_storage_id(uint64_t value) {
  
  _impl_.storage_id_ = value;
}
inline void BlobReference::set_storage_id(uint64_t value) {
  _internal_set_storage_id(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.BlobReference.storage_id)
}

// uint64 object_id = 2;
inline void BlobReference::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t BlobReference::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t BlobReference::object_id() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.BlobReference.object_id)
  return _internal_object_id();
}
inline void BlobReference::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void BlobReference::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.BlobReference.object_id)
}

// uint64 tag = 3;
inline void BlobReference::clear_tag() {
  _impl_.tag_ = uint64_t{0u};
}
inline uint64_t BlobReference::_internal_tag() const {
  return _impl_.tag_;
}
inline uint64_t BlobReference::tag() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.BlobReference.tag)
  return _internal_tag();
}
inline void BlobReference::_internal_set_tag(uint64_t value) {
  
  _impl_.tag_ = value;
}
inline void BlobReference::set_tag(uint64_t value) {
  _internal_set_tag(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.BlobReference.tag)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace blob_relay
}  // namespace data_relay_grpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_blob_5freference_2eproto
