// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blob_relay_streaming.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_blob_5frelay_5fstreaming_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_blob_5frelay_5fstreaming_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "blob_reference.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_blob_5frelay_5fstreaming_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_blob_5frelay_5fstreaming_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_blob_5frelay_5fstreaming_2eproto;
namespace data_relay_grpc {
namespace blob_relay {
namespace proto {
class GetStreamingRequest;
struct GetStreamingRequestDefaultTypeInternal;
extern GetStreamingRequestDefaultTypeInternal _GetStreamingRequest_default_instance_;
class GetStreamingResponse;
struct GetStreamingResponseDefaultTypeInternal;
extern GetStreamingResponseDefaultTypeInternal _GetStreamingResponse_default_instance_;
class PutStreamingRequest;
struct PutStreamingRequestDefaultTypeInternal;
extern PutStreamingRequestDefaultTypeInternal _PutStreamingRequest_default_instance_;
class PutStreamingRequest_Metadata;
struct PutStreamingRequest_MetadataDefaultTypeInternal;
extern PutStreamingRequest_MetadataDefaultTypeInternal _PutStreamingRequest_Metadata_default_instance_;
class PutStreamingResponse;
struct PutStreamingResponseDefaultTypeInternal;
extern PutStreamingResponseDefaultTypeInternal _PutStreamingResponse_default_instance_;
}  // namespace proto
}  // namespace blob_relay
}  // namespace data_relay_grpc
PROTOBUF_NAMESPACE_OPEN
template<> ::data_relay_grpc::blob_relay::proto::GetStreamingRequest* Arena::CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::GetStreamingRequest>(Arena*);
template<> ::data_relay_grpc::blob_relay::proto::GetStreamingResponse* Arena::CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::GetStreamingResponse>(Arena*);
template<> ::data_relay_grpc::blob_relay::proto::PutStreamingRequest* Arena::CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::PutStreamingRequest>(Arena*);
template<> ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* Arena::CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata>(Arena*);
template<> ::data_relay_grpc::blob_relay::proto::PutStreamingResponse* Arena::CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::PutStreamingResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace data_relay_grpc {
namespace blob_relay {
namespace proto {

// ===================================================================

class GetStreamingRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:data_relay_grpc.blob_relay.proto.GetStreamingRequest) */ {
 public:
  inline GetStreamingRequest() : GetStreamingRequest(nullptr) {}
  ~GetStreamingRequest() override;
  explicit PROTOBUF_CONSTEXPR GetStreamingRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetStreamingRequest(const GetStreamingRequest& from);
  GetStreamingRequest(GetStreamingRequest&& from) noexcept
    : GetStreamingRequest() {
    *this = ::std::move(from);
  }

  inline GetStreamingRequest& operator=(const GetStreamingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetStreamingRequest& operator=(GetStreamingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetStreamingRequest& default_instance() {
    return *internal_default_instance();
  }
  enum ContextIdCase {
    kSessionId = 2,
    kTransactionId = 3,
    CONTEXT_ID_NOT_SET = 0,
  };

  static inline const GetStreamingRequest* internal_default_instance() {
    return reinterpret_cast<const GetStreamingRequest*>(
               &_GetStreamingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetStreamingRequest& a, GetStreamingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetStreamingRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetStreamingRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetStreamingRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetStreamingRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetStreamingRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetStreamingRequest& from) {
    GetStreamingRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStreamingRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "data_relay_grpc.blob_relay.proto.GetStreamingRequest";
  }
  protected:
  explicit GetStreamingRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlobFieldNumber = 4,
    kApiVersionFieldNumber = 1,
    kSessionIdFieldNumber = 2,
    kTransactionIdFieldNumber = 3,
  };
  // .data_relay_grpc.blob_relay.proto.BlobReference blob = 4;
  bool has_blob() const;
  private:
  bool _internal_has_blob() const;
  public:
  void clear_blob();
  const ::data_relay_grpc::blob_relay::proto::BlobReference& blob() const;
  PROTOBUF_NODISCARD ::data_relay_grpc::blob_relay::proto::BlobReference* release_blob();
  ::data_relay_grpc::blob_relay::proto::BlobReference* mutable_blob();
  void set_allocated_blob(::data_relay_grpc::blob_relay::proto::BlobReference* blob);
  private:
  const ::data_relay_grpc::blob_relay::proto::BlobReference& _internal_blob() const;
  ::data_relay_grpc::blob_relay::proto::BlobReference* _internal_mutable_blob();
  public:
  void unsafe_arena_set_allocated_blob(
      ::data_relay_grpc::blob_relay::proto::BlobReference* blob);
  ::data_relay_grpc::blob_relay::proto::BlobReference* unsafe_arena_release_blob();

  // uint64 api_version = 1;
  void clear_api_version();
  uint64_t api_version() const;
  void set_api_version(uint64_t value);
  private:
  uint64_t _internal_api_version() const;
  void _internal_set_api_version(uint64_t value);
  public:

  // uint64 session_id = 2;
  bool has_session_id() const;
  private:
  bool _internal_has_session_id() const;
  public:
  void clear_session_id();
  uint64_t session_id() const;
  void set_session_id(uint64_t value);
  private:
  uint64_t _internal_session_id() const;
  void _internal_set_session_id(uint64_t value);
  public:

  // uint64 transaction_id = 3;
  bool has_transaction_id() const;
  private:
  bool _internal_has_transaction_id() const;
  public:
  void clear_transaction_id();
  uint64_t transaction_id() const;
  void set_transaction_id(uint64_t value);
  private:
  uint64_t _internal_transaction_id() const;
  void _internal_set_transaction_id(uint64_t value);
  public:

  void clear_context_id();
  ContextIdCase context_id_case() const;
  // @@protoc_insertion_point(class_scope:data_relay_grpc.blob_relay.proto.GetStreamingRequest)
 private:
  class _Internal;
  void set_has_session_id();
  void set_has_transaction_id();

  inline bool has_context_id() const;
  inline void clear_has_context_id();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::data_relay_grpc::blob_relay::proto::BlobReference* blob_;
    uint64_t api_version_;
    union ContextIdUnion {
      constexpr ContextIdUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      uint64_t session_id_;
      uint64_t transaction_id_;
    } context_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_blob_5frelay_5fstreaming_2eproto;
};
// -------------------------------------------------------------------

class GetStreamingResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:data_relay_grpc.blob_relay.proto.GetStreamingResponse) */ {
 public:
  inline GetStreamingResponse() : GetStreamingResponse(nullptr) {}
  ~GetStreamingResponse() override;
  explicit PROTOBUF_CONSTEXPR GetStreamingResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetStreamingResponse(const GetStreamingResponse& from);
  GetStreamingResponse(GetStreamingResponse&& from) noexcept
    : GetStreamingResponse() {
    *this = ::std::move(from);
  }

  inline GetStreamingResponse& operator=(const GetStreamingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetStreamingResponse& operator=(GetStreamingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetStreamingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetStreamingResponse* internal_default_instance() {
    return reinterpret_cast<const GetStreamingResponse*>(
               &_GetStreamingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetStreamingResponse& a, GetStreamingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetStreamingResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetStreamingResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetStreamingResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetStreamingResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetStreamingResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetStreamingResponse& from) {
    GetStreamingResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStreamingResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "data_relay_grpc.blob_relay.proto.GetStreamingResponse";
  }
  protected:
  explicit GetStreamingResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChunkFieldNumber = 1,
  };
  // bytes chunk = 1;
  void clear_chunk();
  const std::string& chunk() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_chunk(ArgT0&& arg0, ArgT... args);
  std::string* mutable_chunk();
  PROTOBUF_NODISCARD std::string* release_chunk();
  void set_allocated_chunk(std::string* chunk);
  private:
  const std::string& _internal_chunk() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_chunk(const std::string& value);
  std::string* _internal_mutable_chunk();
  public:

  // @@protoc_insertion_point(class_scope:data_relay_grpc.blob_relay.proto.GetStreamingResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chunk_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_blob_5frelay_5fstreaming_2eproto;
};
// -------------------------------------------------------------------

class PutStreamingRequest_Metadata final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata) */ {
 public:
  inline PutStreamingRequest_Metadata() : PutStreamingRequest_Metadata(nullptr) {}
  ~PutStreamingRequest_Metadata() override;
  explicit PROTOBUF_CONSTEXPR PutStreamingRequest_Metadata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PutStreamingRequest_Metadata(const PutStreamingRequest_Metadata& from);
  PutStreamingRequest_Metadata(PutStreamingRequest_Metadata&& from) noexcept
    : PutStreamingRequest_Metadata() {
    *this = ::std::move(from);
  }

  inline PutStreamingRequest_Metadata& operator=(const PutStreamingRequest_Metadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline PutStreamingRequest_Metadata& operator=(PutStreamingRequest_Metadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PutStreamingRequest_Metadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const PutStreamingRequest_Metadata* internal_default_instance() {
    return reinterpret_cast<const PutStreamingRequest_Metadata*>(
               &_PutStreamingRequest_Metadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PutStreamingRequest_Metadata& a, PutStreamingRequest_Metadata& b) {
    a.Swap(&b);
  }
  inline void Swap(PutStreamingRequest_Metadata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PutStreamingRequest_Metadata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PutStreamingRequest_Metadata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PutStreamingRequest_Metadata>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PutStreamingRequest_Metadata& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PutStreamingRequest_Metadata& from) {
    PutStreamingRequest_Metadata::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PutStreamingRequest_Metadata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata";
  }
  protected:
  explicit PutStreamingRequest_Metadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiVersionFieldNumber = 1,
    kSessionIdFieldNumber = 2,
  };
  // uint64 api_version = 1;
  void clear_api_version();
  uint64_t api_version() const;
  void set_api_version(uint64_t value);
  private:
  uint64_t _internal_api_version() const;
  void _internal_set_api_version(uint64_t value);
  public:

  // uint64 session_id = 2;
  void clear_session_id();
  uint64_t session_id() const;
  void set_session_id(uint64_t value);
  private:
  uint64_t _internal_session_id() const;
  void _internal_set_session_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t api_version_;
    uint64_t session_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_blob_5frelay_5fstreaming_2eproto;
};
// -------------------------------------------------------------------

class PutStreamingRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:data_relay_grpc.blob_relay.proto.PutStreamingRequest) */ {
 public:
  inline PutStreamingRequest() : PutStreamingRequest(nullptr) {}
  ~PutStreamingRequest() override;
  explicit PROTOBUF_CONSTEXPR PutStreamingRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PutStreamingRequest(const PutStreamingRequest& from);
  PutStreamingRequest(PutStreamingRequest&& from) noexcept
    : PutStreamingRequest() {
    *this = ::std::move(from);
  }

  inline PutStreamingRequest& operator=(const PutStreamingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PutStreamingRequest& operator=(PutStreamingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PutStreamingRequest& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kMetadata = 1,
    kChunk = 2,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const PutStreamingRequest* internal_default_instance() {
    return reinterpret_cast<const PutStreamingRequest*>(
               &_PutStreamingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PutStreamingRequest& a, PutStreamingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PutStreamingRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PutStreamingRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PutStreamingRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PutStreamingRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PutStreamingRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PutStreamingRequest& from) {
    PutStreamingRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PutStreamingRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "data_relay_grpc.blob_relay.proto.PutStreamingRequest";
  }
  protected:
  explicit PutStreamingRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PutStreamingRequest_Metadata Metadata;

  // accessors -------------------------------------------------------

  enum : int {
    kMetadataFieldNumber = 1,
    kChunkFieldNumber = 2,
  };
  // .data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata metadata = 1;
  bool has_metadata() const;
  private:
  bool _internal_has_metadata() const;
  public:
  void clear_metadata();
  const ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata& metadata() const;
  PROTOBUF_NODISCARD ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* release_metadata();
  ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* mutable_metadata();
  void set_allocated_metadata(::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* metadata);
  private:
  const ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata& _internal_metadata() const;
  ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* _internal_mutable_metadata();
  public:
  void unsafe_arena_set_allocated_metadata(
      ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* metadata);
  ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* unsafe_arena_release_metadata();

  // bytes chunk = 2;
  bool has_chunk() const;
  private:
  bool _internal_has_chunk() const;
  public:
  void clear_chunk();
  const std::string& chunk() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_chunk(ArgT0&& arg0, ArgT... args);
  std::string* mutable_chunk();
  PROTOBUF_NODISCARD std::string* release_chunk();
  void set_allocated_chunk(std::string* chunk);
  private:
  const std::string& _internal_chunk() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_chunk(const std::string& value);
  std::string* _internal_mutable_chunk();
  public:

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:data_relay_grpc.blob_relay.proto.PutStreamingRequest)
 private:
  class _Internal;
  void set_has_metadata();
  void set_has_chunk();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* metadata_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chunk_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_blob_5frelay_5fstreaming_2eproto;
};
// -------------------------------------------------------------------

class PutStreamingResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:data_relay_grpc.blob_relay.proto.PutStreamingResponse) */ {
 public:
  inline PutStreamingResponse() : PutStreamingResponse(nullptr) {}
  ~PutStreamingResponse() override;
  explicit PROTOBUF_CONSTEXPR PutStreamingResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PutStreamingResponse(const PutStreamingResponse& from);
  PutStreamingResponse(PutStreamingResponse&& from) noexcept
    : PutStreamingResponse() {
    *this = ::std::move(from);
  }

  inline PutStreamingResponse& operator=(const PutStreamingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PutStreamingResponse& operator=(PutStreamingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PutStreamingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PutStreamingResponse* internal_default_instance() {
    return reinterpret_cast<const PutStreamingResponse*>(
               &_PutStreamingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PutStreamingResponse& a, PutStreamingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PutStreamingResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PutStreamingResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PutStreamingResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PutStreamingResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PutStreamingResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PutStreamingResponse& from) {
    PutStreamingResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PutStreamingResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "data_relay_grpc.blob_relay.proto.PutStreamingResponse";
  }
  protected:
  explicit PutStreamingResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlobFieldNumber = 1,
  };
  // .data_relay_grpc.blob_relay.proto.BlobReference blob = 1;
  bool has_blob() const;
  private:
  bool _internal_has_blob() const;
  public:
  void clear_blob();
  const ::data_relay_grpc::blob_relay::proto::BlobReference& blob() const;
  PROTOBUF_NODISCARD ::data_relay_grpc::blob_relay::proto::BlobReference* release_blob();
  ::data_relay_grpc::blob_relay::proto::BlobReference* mutable_blob();
  void set_allocated_blob(::data_relay_grpc::blob_relay::proto::BlobReference* blob);
  private:
  const ::data_relay_grpc::blob_relay::proto::BlobReference& _internal_blob() const;
  ::data_relay_grpc::blob_relay::proto::BlobReference* _internal_mutable_blob();
  public:
  void unsafe_arena_set_allocated_blob(
      ::data_relay_grpc::blob_relay::proto::BlobReference* blob);
  ::data_relay_grpc::blob_relay::proto::BlobReference* unsafe_arena_release_blob();

  // @@protoc_insertion_point(class_scope:data_relay_grpc.blob_relay.proto.PutStreamingResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::data_relay_grpc::blob_relay::proto::BlobReference* blob_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_blob_5frelay_5fstreaming_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetStreamingRequest

// uint64 api_version = 1;
inline void GetStreamingRequest::clear_api_version() {
  _impl_.api_version_ = uint64_t{0u};
}
inline uint64_t GetStreamingRequest::_internal_api_version() const {
  return _impl_.api_version_;
}
inline uint64_t GetStreamingRequest::api_version() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.GetStreamingRequest.api_version)
  return _internal_api_version();
}
inline void GetStreamingRequest::_internal_set_api_version(uint64_t value) {
  
  _impl_.api_version_ = value;
}
inline void GetStreamingRequest::set_api_version(uint64_t value) {
  _internal_set_api_version(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.GetStreamingRequest.api_version)
}

// uint64 session_id = 2;
inline bool GetStreamingRequest::_internal_has_session_id() const {
  return context_id_case() == kSessionId;
}
inline bool GetStreamingRequest::has_session_id() const {
  return _internal_has_session_id();
}
inline void GetStreamingRequest::set_has_session_id() {
  _impl_._oneof_case_[0] = kSessionId;
}
inline void GetStreamingRequest::clear_session_id() {
  if (_internal_has_session_id()) {
    _impl_.context_id_.session_id_ = uint64_t{0u};
    clear_has_context_id();
  }
}
inline uint64_t GetStreamingRequest::_internal_session_id() const {
  if (_internal_has_session_id()) {
    return _impl_.context_id_.session_id_;
  }
  return uint64_t{0u};
}
inline void GetStreamingRequest::_internal_set_session_id(uint64_t value) {
  if (!_internal_has_session_id()) {
    clear_context_id();
    set_has_session_id();
  }
  _impl_.context_id_.session_id_ = value;
}
inline uint64_t GetStreamingRequest::session_id() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.GetStreamingRequest.session_id)
  return _internal_session_id();
}
inline void GetStreamingRequest::set_session_id(uint64_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.GetStreamingRequest.session_id)
}

// uint64 transaction_id = 3;
inline bool GetStreamingRequest::_internal_has_transaction_id() const {
  return context_id_case() == kTransactionId;
}
inline bool GetStreamingRequest::has_transaction_id() const {
  return _internal_has_transaction_id();
}
inline void GetStreamingRequest::set_has_transaction_id() {
  _impl_._oneof_case_[0] = kTransactionId;
}
inline void GetStreamingRequest::clear_transaction_id() {
  if (_internal_has_transaction_id()) {
    _impl_.context_id_.transaction_id_ = uint64_t{0u};
    clear_has_context_id();
  }
}
inline uint64_t GetStreamingRequest::_internal_transaction_id() const {
  if (_internal_has_transaction_id()) {
    return _impl_.context_id_.transaction_id_;
  }
  return uint64_t{0u};
}
inline void GetStreamingRequest::_internal_set_transaction_id(uint64_t value) {
  if (!_internal_has_transaction_id()) {
    clear_context_id();
    set_has_transaction_id();
  }
  _impl_.context_id_.transaction_id_ = value;
}
inline uint64_t GetStreamingRequest::transaction_id() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.GetStreamingRequest.transaction_id)
  return _internal_transaction_id();
}
inline void GetStreamingRequest::set_transaction_id(uint64_t value) {
  _internal_set_transaction_id(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.GetStreamingRequest.transaction_id)
}

// .data_relay_grpc.blob_relay.proto.BlobReference blob = 4;
inline bool GetStreamingRequest::_internal_has_blob() const {
  return this != internal_default_instance() && _impl_.blob_ != nullptr;
}
inline bool GetStreamingRequest::has_blob() const {
  return _internal_has_blob();
}
inline const ::data_relay_grpc::blob_relay::proto::BlobReference& GetStreamingRequest::_internal_blob() const {
  const ::data_relay_grpc::blob_relay::proto::BlobReference* p = _impl_.blob_;
  return p != nullptr ? *p : reinterpret_cast<const ::data_relay_grpc::blob_relay::proto::BlobReference&>(
      ::data_relay_grpc::blob_relay::proto::_BlobReference_default_instance_);
}
inline const ::data_relay_grpc::blob_relay::proto::BlobReference& GetStreamingRequest::blob() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.GetStreamingRequest.blob)
  return _internal_blob();
}
inline void GetStreamingRequest::unsafe_arena_set_allocated_blob(
    ::data_relay_grpc::blob_relay::proto::BlobReference* blob) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  _impl_.blob_ = blob;
  if (blob) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:data_relay_grpc.blob_relay.proto.GetStreamingRequest.blob)
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* GetStreamingRequest::release_blob() {
  
  ::data_relay_grpc::blob_relay::proto::BlobReference* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* GetStreamingRequest::unsafe_arena_release_blob() {
  // @@protoc_insertion_point(field_release:data_relay_grpc.blob_relay.proto.GetStreamingRequest.blob)
  
  ::data_relay_grpc::blob_relay::proto::BlobReference* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
  return temp;
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* GetStreamingRequest::_internal_mutable_blob() {
  
  if (_impl_.blob_ == nullptr) {
    auto* p = CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::BlobReference>(GetArenaForAllocation());
    _impl_.blob_ = p;
  }
  return _impl_.blob_;
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* GetStreamingRequest::mutable_blob() {
  ::data_relay_grpc::blob_relay::proto::BlobReference* _msg = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:data_relay_grpc.blob_relay.proto.GetStreamingRequest.blob)
  return _msg;
}
inline void GetStreamingRequest::set_allocated_blob(::data_relay_grpc::blob_relay::proto::BlobReference* blob) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  if (blob) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blob));
    if (message_arena != submessage_arena) {
      blob = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blob, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.blob_ = blob;
  // @@protoc_insertion_point(field_set_allocated:data_relay_grpc.blob_relay.proto.GetStreamingRequest.blob)
}

inline bool GetStreamingRequest::has_context_id() const {
  return context_id_case() != CONTEXT_ID_NOT_SET;
}
inline void GetStreamingRequest::clear_has_context_id() {
  _impl_._oneof_case_[0] = CONTEXT_ID_NOT_SET;
}
inline GetStreamingRequest::ContextIdCase GetStreamingRequest::context_id_case() const {
  return GetStreamingRequest::ContextIdCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// GetStreamingResponse

// bytes chunk = 1;
inline void GetStreamingResponse::clear_chunk() {
  _impl_.chunk_.ClearToEmpty();
}
inline const std::string& GetStreamingResponse::chunk() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.GetStreamingResponse.chunk)
  return _internal_chunk();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetStreamingResponse::set_chunk(ArgT0&& arg0, ArgT... args) {
 
 _impl_.chunk_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.GetStreamingResponse.chunk)
}
inline std::string* GetStreamingResponse::mutable_chunk() {
  std::string* _s = _internal_mutable_chunk();
  // @@protoc_insertion_point(field_mutable:data_relay_grpc.blob_relay.proto.GetStreamingResponse.chunk)
  return _s;
}
inline const std::string& GetStreamingResponse::_internal_chunk() const {
  return _impl_.chunk_.Get();
}
inline void GetStreamingResponse::_internal_set_chunk(const std::string& value) {
  
  _impl_.chunk_.Set(value, GetArenaForAllocation());
}
inline std::string* GetStreamingResponse::_internal_mutable_chunk() {
  
  return _impl_.chunk_.Mutable(GetArenaForAllocation());
}
inline std::string* GetStreamingResponse::release_chunk() {
  // @@protoc_insertion_point(field_release:data_relay_grpc.blob_relay.proto.GetStreamingResponse.chunk)
  return _impl_.chunk_.Release();
}
inline void GetStreamingResponse::set_allocated_chunk(std::string* chunk) {
  if (chunk != nullptr) {
    
  } else {
    
  }
  _impl_.chunk_.SetAllocated(chunk, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.chunk_.IsDefault()) {
    _impl_.chunk_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:data_relay_grpc.blob_relay.proto.GetStreamingResponse.chunk)
}

// -------------------------------------------------------------------

// PutStreamingRequest_Metadata

// uint64 api_version = 1;
inline void PutStreamingRequest_Metadata::clear_api_version() {
  _impl_.api_version_ = uint64_t{0u};
}
inline uint64_t PutStreamingRequest_Metadata::_internal_api_version() const {
  return _impl_.api_version_;
}
inline uint64_t PutStreamingRequest_Metadata::api_version() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata.api_version)
  return _internal_api_version();
}
inline void PutStreamingRequest_Metadata::_internal_set_api_version(uint64_t value) {
  
  _impl_.api_version_ = value;
}
inline void PutStreamingRequest_Metadata::set_api_version(uint64_t value) {
  _internal_set_api_version(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata.api_version)
}

// uint64 session_id = 2;
inline void PutStreamingRequest_Metadata::clear_session_id() {
  _impl_.session_id_ = uint64_t{0u};
}
inline uint64_t PutStreamingRequest_Metadata::_internal_session_id() const {
  return _impl_.session_id_;
}
inline uint64_t PutStreamingRequest_Metadata::session_id() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata.session_id)
  return _internal_session_id();
}
inline void PutStreamingRequest_Metadata::_internal_set_session_id(uint64_t value) {
  
  _impl_.session_id_ = value;
}
inline void PutStreamingRequest_Metadata::set_session_id(uint64_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata.session_id)
}

// -------------------------------------------------------------------

// PutStreamingRequest

// .data_relay_grpc.blob_relay.proto.PutStreamingRequest.Metadata metadata = 1;
inline bool PutStreamingRequest::_internal_has_metadata() const {
  return payload_case() == kMetadata;
}
inline bool PutStreamingRequest::has_metadata() const {
  return _internal_has_metadata();
}
inline void PutStreamingRequest::set_has_metadata() {
  _impl_._oneof_case_[0] = kMetadata;
}
inline void PutStreamingRequest::clear_metadata() {
  if (_internal_has_metadata()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.metadata_;
    }
    clear_has_payload();
  }
}
inline ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* PutStreamingRequest::release_metadata() {
  // @@protoc_insertion_point(field_release:data_relay_grpc.blob_relay.proto.PutStreamingRequest.metadata)
  if (_internal_has_metadata()) {
    clear_has_payload();
    ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* temp = _impl_.payload_.metadata_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.metadata_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata& PutStreamingRequest::_internal_metadata() const {
  return _internal_has_metadata()
      ? *_impl_.payload_.metadata_
      : reinterpret_cast< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata&>(::data_relay_grpc::blob_relay::proto::_PutStreamingRequest_Metadata_default_instance_);
}
inline const ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata& PutStreamingRequest::metadata() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.PutStreamingRequest.metadata)
  return _internal_metadata();
}
inline ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* PutStreamingRequest::unsafe_arena_release_metadata() {
  // @@protoc_insertion_point(field_unsafe_arena_release:data_relay_grpc.blob_relay.proto.PutStreamingRequest.metadata)
  if (_internal_has_metadata()) {
    clear_has_payload();
    ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* temp = _impl_.payload_.metadata_;
    _impl_.payload_.metadata_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PutStreamingRequest::unsafe_arena_set_allocated_metadata(::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* metadata) {
  clear_payload();
  if (metadata) {
    set_has_metadata();
    _impl_.payload_.metadata_ = metadata;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:data_relay_grpc.blob_relay.proto.PutStreamingRequest.metadata)
}
inline ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* PutStreamingRequest::_internal_mutable_metadata() {
  if (!_internal_has_metadata()) {
    clear_payload();
    set_has_metadata();
    _impl_.payload_.metadata_ = CreateMaybeMessage< ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata >(GetArenaForAllocation());
  }
  return _impl_.payload_.metadata_;
}
inline ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* PutStreamingRequest::mutable_metadata() {
  ::data_relay_grpc::blob_relay::proto::PutStreamingRequest_Metadata* _msg = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:data_relay_grpc.blob_relay.proto.PutStreamingRequest.metadata)
  return _msg;
}

// bytes chunk = 2;
inline bool PutStreamingRequest::_internal_has_chunk() const {
  return payload_case() == kChunk;
}
inline bool PutStreamingRequest::has_chunk() const {
  return _internal_has_chunk();
}
inline void PutStreamingRequest::set_has_chunk() {
  _impl_._oneof_case_[0] = kChunk;
}
inline void PutStreamingRequest::clear_chunk() {
  if (_internal_has_chunk()) {
    _impl_.payload_.chunk_.Destroy();
    clear_has_payload();
  }
}
inline const std::string& PutStreamingRequest::chunk() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.PutStreamingRequest.chunk)
  return _internal_chunk();
}
template <typename ArgT0, typename... ArgT>
inline void PutStreamingRequest::set_chunk(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_chunk()) {
    clear_payload();
    set_has_chunk();
    _impl_.payload_.chunk_.InitDefault();
  }
  _impl_.payload_.chunk_.SetBytes( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:data_relay_grpc.blob_relay.proto.PutStreamingRequest.chunk)
}
inline std::string* PutStreamingRequest::mutable_chunk() {
  std::string* _s = _internal_mutable_chunk();
  // @@protoc_insertion_point(field_mutable:data_relay_grpc.blob_relay.proto.PutStreamingRequest.chunk)
  return _s;
}
inline const std::string& PutStreamingRequest::_internal_chunk() const {
  if (_internal_has_chunk()) {
    return _impl_.payload_.chunk_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void PutStreamingRequest::_internal_set_chunk(const std::string& value) {
  if (!_internal_has_chunk()) {
    clear_payload();
    set_has_chunk();
    _impl_.payload_.chunk_.InitDefault();
  }
  _impl_.payload_.chunk_.Set(value, GetArenaForAllocation());
}
inline std::string* PutStreamingRequest::_internal_mutable_chunk() {
  if (!_internal_has_chunk()) {
    clear_payload();
    set_has_chunk();
    _impl_.payload_.chunk_.InitDefault();
  }
  return _impl_.payload_.chunk_.Mutable(      GetArenaForAllocation());
}
inline std::string* PutStreamingRequest::release_chunk() {
  // @@protoc_insertion_point(field_release:data_relay_grpc.blob_relay.proto.PutStreamingRequest.chunk)
  if (_internal_has_chunk()) {
    clear_has_payload();
    return _impl_.payload_.chunk_.Release();
  } else {
    return nullptr;
  }
}
inline void PutStreamingRequest::set_allocated_chunk(std::string* chunk) {
  if (has_payload()) {
    clear_payload();
  }
  if (chunk != nullptr) {
    set_has_chunk();
    _impl_.payload_.chunk_.InitAllocated(chunk, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:data_relay_grpc.blob_relay.proto.PutStreamingRequest.chunk)
}

inline bool PutStreamingRequest::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void PutStreamingRequest::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline PutStreamingRequest::PayloadCase PutStreamingRequest::payload_case() const {
  return PutStreamingRequest::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// PutStreamingResponse

// .data_relay_grpc.blob_relay.proto.BlobReference blob = 1;
inline bool PutStreamingResponse::_internal_has_blob() const {
  return this != internal_default_instance() && _impl_.blob_ != nullptr;
}
inline bool PutStreamingResponse::has_blob() const {
  return _internal_has_blob();
}
inline const ::data_relay_grpc::blob_relay::proto::BlobReference& PutStreamingResponse::_internal_blob() const {
  const ::data_relay_grpc::blob_relay::proto::BlobReference* p = _impl_.blob_;
  return p != nullptr ? *p : reinterpret_cast<const ::data_relay_grpc::blob_relay::proto::BlobReference&>(
      ::data_relay_grpc::blob_relay::proto::_BlobReference_default_instance_);
}
inline const ::data_relay_grpc::blob_relay::proto::BlobReference& PutStreamingResponse::blob() const {
  // @@protoc_insertion_point(field_get:data_relay_grpc.blob_relay.proto.PutStreamingResponse.blob)
  return _internal_blob();
}
inline void PutStreamingResponse::unsafe_arena_set_allocated_blob(
    ::data_relay_grpc::blob_relay::proto::BlobReference* blob) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  _impl_.blob_ = blob;
  if (blob) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:data_relay_grpc.blob_relay.proto.PutStreamingResponse.blob)
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* PutStreamingResponse::release_blob() {
  
  ::data_relay_grpc::blob_relay::proto::BlobReference* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* PutStreamingResponse::unsafe_arena_release_blob() {
  // @@protoc_insertion_point(field_release:data_relay_grpc.blob_relay.proto.PutStreamingResponse.blob)
  
  ::data_relay_grpc::blob_relay::proto::BlobReference* temp = _impl_.blob_;
  _impl_.blob_ = nullptr;
  return temp;
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* PutStreamingResponse::_internal_mutable_blob() {
  
  if (_impl_.blob_ == nullptr) {
    auto* p = CreateMaybeMessage<::data_relay_grpc::blob_relay::proto::BlobReference>(GetArenaForAllocation());
    _impl_.blob_ = p;
  }
  return _impl_.blob_;
}
inline ::data_relay_grpc::blob_relay::proto::BlobReference* PutStreamingResponse::mutable_blob() {
  ::data_relay_grpc::blob_relay::proto::BlobReference* _msg = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:data_relay_grpc.blob_relay.proto.PutStreamingResponse.blob)
  return _msg;
}
inline void PutStreamingResponse::set_allocated_blob(::data_relay_grpc::blob_relay::proto::BlobReference* blob) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.blob_);
  }
  if (blob) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blob));
    if (message_arena != submessage_arena) {
      blob = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blob, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.blob_ = blob;
  // @@protoc_insertion_point(field_set_allocated:data_relay_grpc.blob_relay.proto.PutStreamingResponse.blob)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace blob_relay
}  // namespace data_relay_grpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_blob_5frelay_5fstreaming_2eproto
