name: Jogasaki-CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        sharksfin-implementation: [memory, shirakami]
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:${{ matrix.os }}
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install_Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          sharksfin-implementation: ${{ matrix.sharksfin-implementation }}

      - name: CMake_Build_Jogasaki_${{ matrix.sharksfin-implementation }}
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSHARKSFIN_IMPLEMENTATION=${{ matrix.sharksfin-implementation }} -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/.local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          cmake --build . --target all --clean-first

      - name: CTest_Jogasaki_${{ matrix.sharksfin-implementation }}
        env:
          GTEST_OUTPUT: xml
          ASAN_OPTIONS: detect_stack_use_after_return=true
        run: |
          export LSAN_OPTIONS=suppressions=${GITHUB_WORKSPACE}/etc/lsan/suppress.txt
          cd build
          ctest --verbose --timeout 120 -j 20

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
        with:
          matrix: ${{ toJson(matrix) }}

  Analysis:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:ubuntu-22.04
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install_Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          sharksfin-implementation: memory

      - name: CMake_Build_Jogasaki_memory
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSHARKSFIN_IMPLEMENTATION=memory -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/.local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          cmake --build . --target all --clean-first

      - name: Clang-Tidy
        run: |
          python tools/bin/run-clang-tidy.py -quiet -export-fixes=build/clang-tidy-fix.yaml -p build -extra-arg=-Wno-unknown-warning-option -header-filter=$(pwd)'/(include|src)/.*\.h$' $(pwd)'/src/.*' 2>&1 | awk '!a[$0]++{print > "build/clang-tidy.log"}'

      - name: Doxygen
        run: |
          cd build
          ninja doxygen 2> >(tee doxygen-error.log)

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
