name: Jogasaki-CI

on: [push, pull_request]

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        container-tag: [ubuntu-18.04, ubuntu-20.04]
        include:
          - container-tag: ubuntu-18.04
            additional_prefix_path: /opt/bison-3.5.1
    runs-on: [self-hosted, docker]
    timeout-minutes: 30
    container:
      image:  ghcr.io/project-tsurugi/oltp-sandbox:${{ matrix.container-tag }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    defaults:
      run:
        shell: bash

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GHA_PAT }}

      - id: Install_shirakami
        name: Install_shirakami
        run: |
          cd third_party/sharksfin/third_party/shirakami
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITIZER=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_sharksfin
        name: Install_sharksfin
        run: |
          cd third_party/sharksfin
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_EXAMPLES=OFF -DFORCE_INSTALL_RPATH=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_fpdecimal
        name: Install_fpdecimal
        run: |
          cd third_party/mizugaki/third_party/yugawara/third_party/takatori/third_party/fpdecimal
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_takatori
        name: Install_takatori
        run: |
          cd third_party/mizugaki/third_party/yugawara/third_party/takatori
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DFORCE_INSTALL_RPATH=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_hopscotch-map
        name: Install_hopscotch-map
        run: |
          cd third_party/mizugaki/third_party/hopscotch-map
          rm -rf ../../build-hopscotch-map
          mkdir -p ../../build-hopscotch-map
          cd ../../build-hopscotch-map
          cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ../third_party/hopscotch-map
          cmake --build . --target install -- -j

      - id: Install_yugawara
        name: Install_yugawara
        run: |
          cd third_party/mizugaki/third_party/yugawara
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DFORCE_INSTALL_RPATH=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_shakujo
        name: Install_shakujo
        run: |
          cd third_party/mizugaki/third_party/shakujo
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_mizugaki
        name: Install_mizugaki
        run: |
          cd third_party/mizugaki
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DFORCE_INSTALL_RPATH=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local -DCMAKE_PREFIX_PATH="${{ matrix.additional_prefix_path }};${GITHUB_WORKSPACE}/.local" ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_performance_tools
        name: Install_performance_tools
        run: |
          cd third_party/performance-tools
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j

      - id: Install_moodycamel_concurrentqueue
        name: Install_moodycamel_concurrentqueue
        run: |
          cd third_party/concurrentqueue
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first

      - id: Install_tateyama_memory
        name: Install_tateyama_memory
        run: |
          cd third_party/tateyama
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DSHARKSFIN_IMPLEMENTATION=memory -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DFORCE_INSTALL_RPATH=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local -DCMAKE_PREFIX_PATH="${{ matrix.additional_prefix_path }};${GITHUB_WORKSPACE}/.local" ..
          cmake --build . --target install --clean-first -- -j

      - id: Build_jogasaki_memory
        name: Build_jogasaki_memory
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DSHARKSFIN_IMPLEMENTATION=memory -DWITH_OGAWAYAMA=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target all --clean-first -- -j

      - id: Test_jogasaki_memory
        name: Test_jogasaki_memory
        continue-on-error: false
        env:
          GTEST_OUTPUT: xml
          ASAN_OPTIONS: detect_stack_use_after_return=true
        run: |
          cd build
          ctest --verbose -j 100

      - id: Install_tateyama_shirakami
        name: Install_tateyama_shirakami
        run: |
          cd third_party/tateyama
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DSHARKSFIN_IMPLEMENTATION=shirakami -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DFORCE_INSTALL_RPATH=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local -DCMAKE_PREFIX_PATH="${{ matrix.additional_prefix_path }};${GITHUB_WORKSPACE}/.local" ..
          cmake --build . --target install --clean-first -- -j

      - id: Build_jogasaki_shirakami
        name: Build_jogasaki_shirakami
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DSHARKSFIN_IMPLEMENTATION=shirakami -DWITH_OGAWAYAMA=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target all --clean-first -- -j

      - id: Test_jogasaki_shirakami
        name: Test_jogasaki_shirakami
        continue-on-error: false
        env:
          GTEST_OUTPUT: xml
          ASAN_OPTIONS: detect_stack_use_after_return=true
        run: |
          cd build
          ctest --verbose -j 100

      - id: Clang-Tidy
        name: Clang-Tidy
        run: |
          python tools/bin/run-clang-tidy.py -quiet -export-fixes=build/clang-tidy-fix.yaml -p build -extra-arg=-Wno-unknown-warning-option -header-filter=$(pwd)'/(include|src)/.*\.h$' $(pwd)'/src/.*' 2>&1 | tee build/clang-tidy.log
        if: matrix.container-tag != 'ubuntu-18.04'

      - id: Doxygen
        name: Doxygen
        run: |
          cd build
          make doxygen 2> >(tee doxygen-error.log)
        if: matrix.container-tag != 'ubuntu-18.04'

      - id: Generate_Annotations
        name: Generate_Annotations
        uses: ./.github/actions/tsurugi-annotations-action
        if: always()
        with:
          matrix: ${{ toJson(matrix) }}
          ctest_input: 'build*/**/*_gtest_result.xml'

      - id: Notify_Slack
        name: Notify_Slack
        uses: ./.github/actions/tsurugi-slack-action
        if: always() && (contains(github.ref, '/tags/') || contains(github.ref, '/pull/') || contains(github.ref, '/heads/master'))
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          kind: 'job-result'
          channel: 'tsurugi-build'
          status: ${{ job.status }}
          step_context: ${{ toJson(steps) }}
          username: ${{ github.workflow }}
