name: Jogasaki-CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      os:
        type: string
        default: 'ubuntu-22.04'
      cmake_build_option:
        type: string
        default: ''

jobs:
  Test:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:${{ inputs.os || 'ubuntu-22.04' }}
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/${{ inputs.os || 'ubuntu-22.04' }}
      SHARKSFIN_IMPLEMENTATION: shirakami

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install_Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          sharksfin_implementation: ${{ env.SHARKSFIN_IMPLEMENTATION }}
          cmake_build_option: ${{ inputs.cmake_build_option }}

      - name: CMake_Build
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSHARKSFIN_IMPLEMENTATION=${SHARKSFIN_IMPLEMENTATION} -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/.local -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DBUILD_DOCUMENTS=ON ${{ inputs.cmake_build_option }} ..
          cmake --build . --target all --clean-first

      - name: CTest
        env:
          GTEST_OUTPUT: xml
          ASAN_OPTIONS: detect_stack_use_after_return=true
        run: |
          export LSAN_OPTIONS=suppressions=${GITHUB_WORKSPACE}/etc/lsan/suppress.txt
          cd build
          ctest --verbose --timeout 240 -j 16

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()

  Analysis:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:ubuntu-22.04
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/ubuntu-22.04
      SHARKSFIN_IMPLEMENTATION: memory

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install_Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          sharksfin_implementation: ${{ env.SHARKSFIN_IMPLEMENTATION }}
          cmake_build_option: ${{ inputs.cmake_build_option }}

      - name: CMake_Build
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSHARKSFIN_IMPLEMENTATION=${SHARKSFIN_IMPLEMENTATION} -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/.local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DBUILD_DOCUMENTS=ON ${{ inputs.cmake_build_option }} ..
          cmake --build . --target all --clean-first

      - name: Clang-Tidy
        run: |
          python tools/bin/run-clang-tidy.py -quiet -export-fixes=build/clang-tidy-fix.yaml -p build -extra-arg=-Wno-unknown-warning-option -header-filter=$(pwd)'/(include|src)/.*\.h$' $(pwd)'/src/.*' 2>&1 | awk '!a[$0]++{print > "build/clang-tidy.log"}'

      - name: Doxygen
        run: |
          cd build
          ninja doxygen 2> >(tee doxygen-error.log)

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
